Msi\Bundle\MessageBundle\Entity\Message:
    properties:
        subject:
            - NotBlank: ~
        body:
            - NotBlank: ~
        recipients:
            - Count:
                min: 1
